import { Box } from "@chakra-ui/react";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Catalogo } from "~/components/Catalogo/Catalogo";
import { PanelMesas } from "~/components/PanelMesas/PanelMesas";
import { Sidebar } from "~/components/Sidebar/Sidebar";


const Overview: NextPage = () => {
  const [display, displaySet] = useState<string>('');
  function switchRender(arg: string) {
    switch(arg){
      case 'Panel':
        return <PanelMesas/>  
      case 'Catalogo':
        return <Catalogo/>
      case 'Estadisticas':
        return <Box>Estadicas</Box>
      case 'Reservas':
        return <Box>Reservas</Box>
      default:
        return <PanelMesas/>
    }
  }
  
    return (
      <>
        <Head>
          <title>Polaridades Menu App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen justify-center bg-gradient-to-b from-[#c20404] to-[#310d0d]">
          <Sidebar displaySet={displaySet} />
          {
            switchRender(display)
          }

        </main>
      </>
    );
  };
  
  export default Overview;